using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace BigFishHelper;

/// <summary>Addon, dem ein Big Fish zuzuordnen ist (siehe BigFishData.ByExpansion) - für die Tabs auf der Fischdaten-Seite.</summary>
public enum BigFishExpansion
{
    ARealmReborn,
    Heavensward,
    Stormblood,
    Shadowbringers,
    Endwalker,
    Dawntrail,
}

/// <summary>
/// Ein Big Fish mit seinen Spawn-Bedingungen. Zeiten in Eorzea-Stunden (0-24, EndHour kann kleiner
/// als StartHour sein = über Mitternacht), Wetter als Lumina-Weather-RowIds (leer = egal).
/// PreviousWeatherSet = Wetter der vorherigen Wetterperiode (8 Eorzea-Stunden davor).
/// Predators = Fische, die für den "Fischer-Intuition"-Buff vorher gefangen werden müssen (Fisch-ItemId, Anzahl).
/// BaitIds = benötigter Köder (Item-Ids, mehrere = gleichwertige Alternativen), MoochPath = Fische, die
/// danach der Reihe nach gemoocht werden (leer = direkt mit dem Köder). Expansion wird bei allen
/// bisherigen (Dawntrail-)Einträgen weggelassen und fällt daher auf den Default zurück.
/// </summary>
public sealed record BigFish(
    uint ItemId,
    uint FishingSpotId,
    uint TerritoryId,
    float StartHour,
    float EndHour,
    uint[] WeatherSet,
    uint[] PreviousWeatherSet,
    (uint FishId, int Count)[] Predators,
    float Patch,
    uint[] BaitIds,
    uint[] MoochPath,
    BigFishExpansion Expansion = BigFishExpansion.Dawntrail);

/// <summary>
/// Big Fish aller Addons, erzeugt aus den Daten des FFXIV Fish Tracker
/// (https://github.com/icykoneko/ff14-fish-tracker-app, js/app/data.js: bigFish = true).
/// Namen/Orte kommen zur Laufzeit aus Lumina (Item/FishingSpot) in der Client-Sprache.
/// </summary>
// Angel-Positionen stehen in Data/FishingPositions.json (siehe FishingPositionStore).
public static class BigFishData
{
    public static readonly BigFish[] ARealmReborn =
    {
        new(7678, 37, 134, 9f, 14f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Zalera (Zephyr Drift) - Rat Tail
        new(7679, 39, 134, 9f, 14f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2586 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Beguiler Chub (Rogue River) - Moth Pupa
        new(7680, 44, 135, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Oschon's Print (Moraby Bay) - Goby Ball
        new(7681, 43, 135, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2586 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Caterwauler (The Mourning Widow) - Moth Pupa
        new(7682, 42, 134, 0f, 24f, new uint[] { 4, 3, 5 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2594 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Crystal Perch (Woad Whisper Canyon) - Butterworm
        new(7683, 8, 152, 18f, 2f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2592 }, new uint[] { 4942 }, Expansion: BigFishExpansion.ARealmReborn), // Moldva (Springripple Brook) - Midge Basket > Ala Mhigan Fighting Fish
        new(7684, 60, 138, 16f, 2f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2585 }, new uint[] { 4869, 4904 }, Expansion: BigFishExpansion.ARealmReborn), // Junkmonger (Skull Valley) - Lugworm > Merlthor Goby > Wahoo
        new(7685, 36, 128, 9f, 14f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2587 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Goldenfin (Limsa Lominsa Upper Decks) - Pill Bug
        new(7686, 38, 134, 0f, 24f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2611 }, new uint[] { 4874 }, Expansion: BigFishExpansion.ARealmReborn), // Gigantshark (Summerford) - Floating Minnow > Harbor Herring
        new(7687, 59, 138, 19f, 3f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2606 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Armorer (Swiftperch) - Northern Krill
        new(7688, 40, 134, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2588 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Great Gudgeon (West Agelyss River) - Crayfish Ball
        new(7689, 77, 141, 0f, 24f, new uint[] { 4, 3, 11 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2614 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Dark Knight (The Unholy Heir) - Crow Fly
        new(7690, 47, 135, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2628 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Silver Sovereign (Oschon's Torch) - Yumizuno
        new(7691, 49, 135, 16f, 22f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Sabertooth Cod (Candlekeep Quay) - Goby Ball
        new(7692, 75, 141, 17f, 3f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2588 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Dream Goby (Upper Soot Creek) - Crayfish Ball
        new(7693, 64, 138, 9f, 14f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2628 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Navigator's Brand (The Brewer's Beacon) - Yumizuno
        new(7694, 6, 152, 21f, 3f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2586 }, new uint[] { 4927 }, Expansion: BigFishExpansion.ARealmReborn), // Dark Ambusher (Sweetbloom Pier) - Moth Pupa > Striped Goby
        new(7695, 19, 154, 17f, 21f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2623 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Judgeray (Fallgourd Float) - Wildfowl Fly
        new(7696, 91, 132, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2588 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Bloody Brewer (Lower Black Tea Brook) - Crayfish Ball
        new(7697, 50, 135, 0f, 24f, new uint[] { 4, 3, 5 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2626 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Faerie Queen (Empty Heart) - Spinnerbait
        new(7698, 76, 141, 19f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2588 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Slime King (Lower Soot Creek) - Crayfish Ball
        new(7699, 18, 154, 9f, 14f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2611 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Blue Widow (Murmur Rills) - Floating Minnow
        new(7700, 3, 148, 21f, 3f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2594 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Ghost Carp (The Mirror) - Butterworm
        new(7701, 100, 133, 9f, 14f, new uint[] { 4, 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2614 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Carp Diem (Upper Black Tea Brook) - Crow Fly
        new(7702, 79, 145, 17f, 7f, new uint[] { 7, 8 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2592 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Mud Pilgrim (South Drybone) - Midge Basket
        new(7703, 96, 141, 17f, 21f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Old Softie (The Clutch) - Bloodworm
        new(7704, 78, 145, 20f, 3f, new uint[] { 7, 8 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2597 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Marrow Sucker (North Drybone) - Syrphid Basket
        new(7705, 2, 148, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2586 }, new uint[] { 4927 }, Expansion: BigFishExpansion.ARealmReborn), // Chirurgeon (The Vein) - Moth Pupa > Striped Goby
        new(7706, 73, 140, 21f, 3f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2594 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Mud Golem (The Footfalls) - Butterworm
        new(7707, 35, 129, 9f, 17f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2587 }, new uint[] { 4874 }, Expansion: BigFishExpansion.ARealmReborn), // Octomammoth (Limsa Lominsa Lower Decks) - Pill Bug > Harbor Herring
        new(7708, 81, 133, 15f, 21f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Matron Carp (Whispering Gorge) - Bloodworm
        new(7709, 41, 134, 5f, 8f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2617 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // High Perch (Nym River) - Sinking Minnow
        new(7710, 45, 135, 0f, 24f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2596 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Syldra (Cedarwood) - Spoon Worm
        new(7711, 70, 140, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Rivet Oyster (Vesper Bay) - Heavy Steel Jig
        new(7712, 46, 135, 21f, 3f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Jacques the Snipper (Moraby Drydocks) - Goby Ball
        new(7713, 90, 132, 17f, 2f, new uint[] { 7, 15 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2601 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Stormdancer (Jadeite Flood) - Stem Borer
        new(7714, 72, 140, 0f, 24f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.2f, new uint[] { 2594 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Glimmerscale (Nophica's Wells) - Butterworm
        new(7902, 97, 135, 17f, 18.5f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2597 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Cupfish (Blind Iron Mines) - Syrphid Basket
        new(7903, 48, 135, 3f, 5f, new uint[] { 3, 4, 5 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Meteor Survivor (The Salt Strand) - Rat Tail
        new(7904, 67, 139, 4f, 6f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2614 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Joan of Trout (Fool Falls) - Crow Fly
        new(7905, 66, 139, 17f, 19.5f, new uint[] { 3, 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2620 }, new uint[] { 4995 }, Expansion: BigFishExpansion.ARealmReborn), // Toramafish (Oakwood) - Spinner > Common Sculpin
        new(7906, 71, 140, 17.5f, 18f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2606 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Fingers (Crescent Cove) - Northern Krill
        new(7907, 10, 152, 21f, 23f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2594 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Assassin (Sanctum of the Twelve) - Butterworm
        new(7908, 11, 153, 18f, 19f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2594 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Vip Viper (Upper Hathoeva River) - Butterworm
        new(7909, 51, 137, 20f, 23f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2613 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Greatest Bream in the World (South Bloodshore) - Shrimp Cage Feeder
        new(7910, 69, 140, 20f, 22f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2606 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Dirty Herry (The Silver Bazaar) - Northern Krill
        new(7911, 83, 146, 0f, 24f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2592 }, new uint[] { 4948 }, Expansion: BigFishExpansion.ARealmReborn), // Old Hollow Eyes (Burnt Lizard Creek) - Midge Basket > Copperfish
        new(7912, 7, 152, 0f, 24f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2594 }, new uint[] { 4948 }, Expansion: BigFishExpansion.ARealmReborn), // Sylphsbane (Verdant Drop) - Butterworm > Copperfish
        new(7913, 13, 153, 0f, 8f, new uint[] { 4, 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2595 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Floating Boulder (Lower Hathoeva River) - Bass Ball
        new(7914, 14, 153, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2597 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Grinner (East Hathoeva River) - Syrphid Basket
        new(7915, 52, 137, 19f, 21f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2596 }, new uint[] { 4898 }, Expansion: BigFishExpansion.ARealmReborn), // Shark Tuna (Costa del Sol) - Spoon Worm > Fullmoon Sardine
        new(7916, 98, 139, 19f, 22f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2594 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Worm of Nym (Bronze Lake Shallows) - Butterworm
        new(7917, 104, 339, 4f, 6f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2596 }, new uint[] { 4898 }, Expansion: BigFishExpansion.ARealmReborn), // Twitchbeard (Mist) - Spoon Worm > Fullmoon Sardine
        new(7918, 80, 145, 17.5f, 20f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2599 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Warden's Wand (Yugr'am River) - Honey Worm
        new(7919, 106, 341, 21f, 24f, new uint[] { 4, 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2607 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Spearnose (The Goblet) - Caddisfly Larva
        new(7920, 4, 148, 18f, 23f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2597 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Levinlight (Everschade) - Syrphid Basket
        new(7921, 12, 153, 21.5f, 3f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2617 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Sinker (Middle Hathoeva River) - Sinking Minnow
        new(7922, 15, 153, 0f, 24f, new uint[] { 9, 10 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2599 }, new uint[] { 4978 }, Expansion: BigFishExpansion.ARealmReborn), // The Gobfather (Goblinblood) - Honey Worm > Silverfish
        new(7923, 105, 340, 23f, 4f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2592 }, new uint[] { 4942 }, Expansion: BigFishExpansion.ARealmReborn), // Sweetnewt (The Lavender Beds) - Midge Basket > Ala Mhigan Fighting Fish
        new(7924, 53, 137, 9f, 15f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2598 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Bombardfish (North Bloodshore) - Herring Ball
        new(7925, 54, 137, 17f, 20f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2599 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Salter (Hidden Falls) - Honey Worm
        new(7926, 61, 138, 0f, 24f, new uint[] { 6 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Lone Ripper (Halfstone) - Heavy Steel Jig
        new(7927, 155, 180, 16f, 18.75f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2626 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // King of the Spring (Northwest Bronze Lake) - Spinnerbait
        new(7928, 84, 146, 12f, 18f, new uint[] { 14 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2603 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Discobolus (Zahar'ak) - Glowworm
        new(7929, 85, 146, 0f, 24f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2620 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Iron Noose (Forgotten Springs) - Spinner
        new(7930, 87, 146, 0f, 24f, new uint[] { 14 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2600 }, new uint[] { 5035 }, Expansion: BigFishExpansion.ARealmReborn), // Olgoi-Khorkhoi (Sagolii Dunes) - Sand Leech > Storm Rider
        new(7931, 86, 146, 9f, 16f, new uint[] { 14 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2600 }, new uint[] { 5035 }, Expansion: BigFishExpansion.ARealmReborn), // Magic Carpet (Sagolii Desert) - Sand Leech > Storm Rider
        new(7932, 26, 155, 0f, 24f, new uint[] { 16 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2623 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Daniffen's Mark (Coerthas River) - Wildfowl Fly
        new(7933, 31, 155, 22f, 4f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2603 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Charon's Lantern (Daniffen Pass) - Glowworm
        new(7934, 5, 148, 18f, 21f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2599 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Green Jester (Hopeseed Pond) - Honey Worm
        new(7935, 92, 148, 0f, 24f, new uint[] { 9 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2599 }, new uint[] { 4978 }, Expansion: BigFishExpansion.ARealmReborn), // Bloodbath (Haukke Manor) - Honey Worm > Silverfish
        new(7936, 16, 153, 0f, 24f, new uint[] { 10 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2607 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Son of Levin (Rootslake) - Caddisfly Larva
        new(7937, 99, 180, 19.5f, 2.75f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2601 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Thundergut (The Long Climb) - Stem Borer
        new(7938, 55, 137, 0f, 24f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2618 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Drowned Sniper (East Agelyss River) - Snurble Fly
        new(7939, 56, 137, 0f, 24f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2599 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Terpsichorean (Raincatcher Gully) - Honey Worm
        new(7940, 57, 137, 9f, 16f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2592 }, new uint[] { 4948 }, Expansion: BigFishExpansion.ARealmReborn), // Mirrorscale (The Juggernaut) - Midge Basket > Copperfish
        new(7941, 62, 138, 9f, 15f, new uint[] { 4, 3, 5 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2587 }, new uint[] { 4872 }, Expansion: BigFishExpansion.ARealmReborn), // Helmsman's Hand (Isles of Umbra Northshore) - Pill Bug > Ocean Cloud
        new(7942, 82, 145, 0f, 24f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2601 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // The Thousand-year Itch (The Burning Wall) - Stem Borer
        new(7943, 89, 147, 22f, 4f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2626 }, new uint[] { 4995 }, Expansion: BigFishExpansion.ARealmReborn), // Hannibal (Bluefog) - Spinnerbait > Common Sculpin
        new(7944, 30, 155, 5f, 7f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2623 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Dawn Maiden (Dragonhead Latrines) - Wildfowl Fly
        new(7945, 28, 155, 20f, 4f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2597 }, new uint[] { 4937 }, Expansion: BigFishExpansion.ARealmReborn), // Starbright (The Nail) - Syrphid Basket > Abalathian Smelt
        new(7946, 32, 155, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2599 }, new uint[] { 4937 }, Expansion: BigFishExpansion.ARealmReborn), // The Matriarch (Exploratory Ice Hole) - Honey Worm > Abalathian Smelt
        new(7947, 20, 154, 4.5f, 10f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2624 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Shadowstreak (Proud Creek) - Topwater Frog
        new(7948, 101, 138, 23.5f, 1.0833333333333333f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2616 }, new uint[] { 4898 }, Expansion: BigFishExpansion.ARealmReborn), // The Captain's Chalice (Sapsa Spawning Grounds) - Steel Jig > Fullmoon Sardine
        new(7949, 34, 155, 10f, 15f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2605 }, new uint[] { 5040 }, Expansion: BigFishExpansion.ARealmReborn), // Anomalocaris (Sea of Clouds) - Hoverworm > Cloud Cutter
        new(7950, 65, 138, 17f, 3f, new uint[] { 4, 3, 5 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2585 }, new uint[] { 4869, 4904, 4919 }, Expansion: BigFishExpansion.ARealmReborn), // Frilled Shark (The Ship Graveyard) - Lugworm > Merlthor Goby > Wahoo > Giant Squid
        new(7951, 22, 156, 3f, 13f, new uint[] { 17 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.3f, new uint[] { 2603 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Aetherlouse (North Silvertear) - Glowworm
        new(8752, 58, 137, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), new (uint, int)[] { (5031, 3) }, 2.4f, new uint[] { 2599 }, new uint[] { 4978 }, Expansion: BigFishExpansion.ARealmReborn), // Imperial Goldfish (Red Mantis Falls) - Honey Worm > Silverfish
        new(8753, 107, 137, 0f, 24f, new uint[] { 1 }, new uint[] { 7, 8 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2587 }, new uint[] { 4874, 4888 }, Expansion: BigFishExpansion.ARealmReborn), // The Old Man in the Sea (Rhotano Sea (Privateer Forecastle)) - Pill Bug > Harbor Herring > Ogre Barracuda
        new(8754, 108, 137, 0f, 24f, new uint[] { 7, 8 }, Array.Empty<uint>(), new (uint, int)[] { (4913, 3) }, 2.4f, new uint[] { 2606 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Nepto Dragon (Rhotano Sea (Privateer Sterncastle)) - Northern Krill
        new(8755, 63, 138, 22f, 3f, new uint[] { 4, 3, 5 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2596 }, new uint[] { 4898 }, Expansion: BigFishExpansion.ARealmReborn), // Coelacanthus (Isles of Umbra Southshore) - Spoon Worm > Fullmoon Sardine
        new(8756, 63, 138, 20f, 4f, new uint[] { 4, 3, 5 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2596 }, new uint[] { 4898 }, Expansion: BigFishExpansion.ARealmReborn), // Endoceras (Isles of Umbra Southshore) - Spoon Worm > Fullmoon Sardine
        new(8757, 102, 138, 19f, 2f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2585 }, new uint[] { 4869, 4904 }, Expansion: BigFishExpansion.ARealmReborn), // Seahag (Reaver Hide) - Lugworm > Merlthor Goby > Wahoo
        new(8758, 25, 156, 0f, 24f, new uint[] { 1, 2 }, new uint[] { 17 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2603 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Ignus Horn (The Deep Tangle) - Glowworm
        new(8759, 23, 156, 0f, 24f, new uint[] { 17 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2603 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Void Bass (Rathefrost) - Glowworm
        new(8760, 21, 154, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), new (uint, int)[] { (5008, 5) }, 2.4f, new uint[] { 2625 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Cornelia (Lake Tahtotl) - Rainbow Spoon Lure
        new(8761, 24, 156, 18f, 9f, new uint[] { 17 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2592 }, new uint[] { 4942, 5002 }, Expansion: BigFishExpansion.ARealmReborn), // Ninja Betta (The Tangle) - Midge Basket > Ala Mhigan Fighting Fish > Assassin Betta
        new(8762, 94, 156, 8f, 18f, new uint[] { 17 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2599 }, new uint[] { 4978, 5011 }, Expansion: BigFishExpansion.ARealmReborn), // Canavan (The North Shards) - Honey Worm > Silverfish > Goldfish
        new(8763, 94, 156, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), new (uint, int)[] { (8762, 1) }, 2.4f, new uint[] { 2599 }, new uint[] { 4978, 5002 }, Expansion: BigFishExpansion.ARealmReborn), // Kuno the Killer (The North Shards) - Honey Worm > Silverfish > Assassin Betta
        new(8764, 74, 140, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), new (uint, int)[] { (4904, 6) }, 2.4f, new uint[] { 2585 }, new uint[] { 4869, 4904 }, Expansion: BigFishExpansion.ARealmReborn), // Pirate's Bane (Cape Westwind) - Lugworm > Merlthor Goby > Wahoo
        new(8765, 103, 140, 18f, 5f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2599 }, new uint[] { 4978, 5002 }, Expansion: BigFishExpansion.ARealmReborn), // Ndendecki (Moondrip) - Honey Worm > Silverfish > Assassin Betta
        new(8766, 95, 140, 0f, 24f, new uint[] { 4, 3, 1, 2 }, new uint[] { 7 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2599 }, new uint[] { 4978 }, Expansion: BigFishExpansion.ARealmReborn), // Bat-o'-Nine-Tails (Parata's Peace) - Honey Worm > Silverfish
        new(8767, 88, 147, 1f, 3.3333333333333335f, new uint[] { 4 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2599 }, new uint[] { 4978 }, Expansion: BigFishExpansion.ARealmReborn), // Wootz Knifefish Zenith (Ceruleum Field) - Honey Worm > Silverfish
        new(8768, 86, 146, 8f, 20f, new uint[] { 14 }, new uint[] { 4, 3 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2600 }, new uint[] { 5035 }, Expansion: BigFishExpansion.ARealmReborn), // Helicoprion (Sagolii Desert) - Sand Leech > Storm Rider
        new(8769, 29, 155, 19f, 4f, new uint[] { 16, 15 }, Array.Empty<uint>(), new (uint, int)[] { (5544, 5) }, 2.4f, new uint[] { 2599 }, new uint[] { 4937 }, Expansion: BigFishExpansion.ARealmReborn), // Darkstar (The Weeping Saint) - Honey Worm > Abalathian Smelt
        new(8770, 33, 155, 0f, 24f, new uint[] { 1, 2 }, new uint[] { 16, 15 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2607 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Blue Corpse (Snowcloak) - Caddisfly Larva
        new(8771, 27, 155, 0f, 24f, new uint[] { 16 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2605 }, new uint[] { 5040 }, Expansion: BigFishExpansion.ARealmReborn), // Mahar (Witchdrop) - Hoverworm > Cloud Cutter
        new(8772, 27, 155, 0f, 24f, new uint[] { 16 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2605 }, new uint[] { 5040, 8771 }, Expansion: BigFishExpansion.ARealmReborn), // Shonisaurus (Witchdrop) - Hoverworm > Cloud Cutter > Mahar
        new(8773, 9, 152, 0f, 24f, new uint[] { 4, 3 }, new uint[] { 7, 9 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2620 }, new uint[] { 4995 }, Expansion: BigFishExpansion.ARealmReborn), // Magicked Mushroom (Sylphlands) - Spinner > Common Sculpin
        new(8774, 17, 153, 0f, 24f, new uint[] { 9, 10 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2603 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Giant Takitaro (Urth's Gift) - Glowworm
        new(8775, 17, 153, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), new (uint, int)[] { (8774, 1) }, 2.4f, new uint[] { 2624 }, Array.Empty<uint>(), Expansion: BigFishExpansion.ARealmReborn), // Namitaro (Urth's Gift) - Topwater Frog
        new(8776, 93, 156, 4.5f, 11.5f, new uint[] { 4 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 2.4f, new uint[] { 2599 }, new uint[] { 4978 }, Expansion: BigFishExpansion.ARealmReborn), // Blood Red Bonytongue (Singing Shards) - Honey Worm > Silverfish
    };

    public static readonly BigFish[] Heavensward =
    {
        new(15626, 109, 397, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Fat Purse (Riversmeet) - Brute Leech
        new(15627, 113, 397, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // The Impaler (Dragonspit) - Brute Leech
        new(15628, 115, 397, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // La Reale (Ashpool) - Brute Leech
        new(15629, 117, 398, 0f, 24f, new uint[] { 11, 4, 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Scaleripper (The Hundred Throes) - Brute Leech
        new(15630, 119, 398, 22f, 2f, new uint[] { 11, 4, 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // The Dreamweaver (The Smoldering Wastes) - Brute Leech
        new(15631, 121, 398, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12709 }, new uint[] { 12754 }, Expansion: BigFishExpansion.Heavensward), // Meteortoise (Mourn) - Magma Worm > Granite Crab
        new(15632, 125, 399, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12707 }, new uint[] { 12780 }, Expansion: BigFishExpansion.Heavensward), // The Ewer King (Thaliak River) - Bladed Steel Jig > Sweetfish
        new(15633, 129, 400, 8f, 10f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Vidofnir (Eil Tohm) - Brute Leech
        new(15634, 132, 400, 4f, 6f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12712 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // The Soul of the Martyr (Landlord Colony) - Giant Crane Fly
        new(15635, 135, 401, 14f, 16f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Inkfish (Voor Sian Siran) - Brute Leech
        new(15636, 138, 401, 0f, 24f, new uint[] { 5 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12712 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // The Second One (The Blue Window) - Giant Crane Fly
        new(15637, 140, 402, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12710 }, new uint[] { 12776 }, Expansion: BigFishExpansion.Heavensward), // Augmented High Allagan Helmet (Alpha Quadrant) - Fiend Worm > Platinum Fish
        new(15638, 143, 402, 21f, 2f, new uint[] { 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.3f, new uint[] { 12705 }, new uint[] { 12777 }, Expansion: BigFishExpansion.Heavensward), // Aphotic Pirarucu (Delta Quadrant) - Purse Web Spider > Aether Eye
        new(16742, 133, 400, 0f, 24f, new uint[] { 6 }, new uint[] { 1 }, Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12712 }, new uint[] { 12805 }, Expansion: BigFishExpansion.Heavensward), // Dimorphodon (Sohm Al Summit) - Giant Crane Fly > Rudderfish
        new(16743, 139, 401, 0f, 24f, new uint[] { 1 }, new uint[] { 4 }, Array.Empty<(uint, int)>(), 3.4f, new uint[] { 28634 }, new uint[] { 12753 }, Expansion: BigFishExpansion.Heavensward), // Basking Shark (Mok Oogl Island) - Metal Spinner > Sky Faerie
        new(16744, 146, 402, 0f, 24f, new uint[] { 9 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 3.4f, new uint[] { 30136 }, new uint[] { 12776 }, Expansion: BigFishExpansion.Heavensward), // Allagan Bladeshark (The Flagship) - Signature Skyball > Platinum Fish
        new(16745, 110, 397, 0f, 24f, new uint[] { 16 }, new uint[] { 16, 15 }, Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12708 }, new uint[] { 12724 }, Expansion: BigFishExpansion.Heavensward), // Hailfinder (Greytail Falls) - Red Balloon > Glacier Core
        new(16746, 111, 397, 10f, 18f, new uint[] { 16 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12705 }, new uint[] { 12715 }, Expansion: BigFishExpansion.Heavensward), // Flarefish (Unfrozen Pond) - Purse Web Spider > Ice Faerie
        new(16747, 118, 398, 12f, 16f, new uint[] { 1 }, new uint[] { 3, 4, 11 }, Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Twin-tongued Carp (Whilom River) - Brute Leech
        new(16748, 126, 399, 21f, 2f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12705 }, new uint[] { 12757 }, Expansion: BigFishExpansion.Heavensward), // Madam Butterfly (Quickspill Delta) - Purse Web Spider > Hedgemole Cricket
        new(16749, 130, 400, 10f, 13f, new uint[] { 1 }, new uint[] { 6 }, Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Moggle Mogpom (Greensward) - Brute Leech
        new(16750, 137, 401, 10f, 13f, new uint[] { 2, 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12712 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Cirrostratus (Cloudtop) - Giant Crane Fly
        new(16751, 122, 398, 2f, 6f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12709 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Hraesvelgr's Tear (West Mourn) - Magma Worm
        new(16752, 141, 402, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12710 }, new uint[] { 12776 }, Expansion: BigFishExpansion.Heavensward), // Aetherochemical Compound #666 (Aetherochemical Spill) - Fiend Worm > Platinum Fish
        new(16753, 144, 402, 6f, 10f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12705 }, new uint[] { 12777 }, Expansion: BigFishExpansion.Heavensward), // Hundred-eyed Axolotl (The Pappus Tree) - Purse Web Spider > Aether Eye
        new(16754, 128, 399, 2f, 6f, new uint[] { 8 }, new uint[] { 7 }, Array.Empty<(uint, int)>(), 3.4f, new uint[] { 12706 }, new uint[] { 12780 }, Expansion: BigFishExpansion.Heavensward), // Bobgoblin Bass (Middle Thaliak River) - Goblin Jig > Sweetfish
        new(16756, 116, 397, 0f, 24f, new uint[] { 16 }, new uint[] { 15, 16 }, Array.Empty<(uint, int)>(), 3.4f, new uint[] { 2607 }, new uint[] { 12715 }, Expansion: BigFishExpansion.Heavensward), // Merciless (West Banepool) - Caddisfly Larva > Ice Faerie
        new(17577, 112, 397, 10f, 14f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Bishopfish (Clearpool) - Brute Leech
        new(17578, 114, 397, 0f, 24f, new uint[] { 16 }, new uint[] { 15 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Captain Nemo (South Banepool) - Brute Leech
        new(17579, 136, 401, 8f, 12f, new uint[] { 1 }, new uint[] { 4 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12707 }, new uint[] { 12730 }, Expansion: BigFishExpansion.Heavensward), // Paikiller (The Eddies) - Bladed Steel Jig > Bullfrog
        new(17580, 142, 402, 18f, 22f, new uint[] { 9 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12710 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Ceti (Hyperstellar Downconverter) - Fiend Worm
        new(17581, 145, 402, 0f, 24f, new uint[] { 9 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12712 }, new uint[] { 12805 }, Expansion: BigFishExpansion.Heavensward), // Crystal Pigeon (The Habisphere) - Giant Crane Fly > Rudderfish
        new(17582, 120, 398, 6f, 8f, new uint[] { 9 }, new uint[] { 11, 3, 4 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12704 }, new uint[] { 12722 }, Expansion: BigFishExpansion.Heavensward), // Thunderscale (The Iron Feast) - Stonefly Nymph > Blueclaw Shrimp
        new(17583, 123, 398, 8f, 16f, new uint[] { 1 }, new uint[] { 1 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12709 }, new uint[] { 12754 }, Expansion: BigFishExpansion.Heavensward), // Riddle (Anyx Old) - Magma Worm > Granite Crab
        new(17584, 124, 398, 8f, 16f, new uint[] { 1, 2 }, new uint[] { 4, 11, 3 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 28634 }, new uint[] { 12754 }, Expansion: BigFishExpansion.Heavensward), // The Lord of Lords (Halo) - Metal Spinner > Granite Crab
        new(17585, 127, 399, 0f, 24f, new uint[] { 8 }, new uint[] { 3, 4 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12704 }, new uint[] { 12757 }, Expansion: BigFishExpansion.Heavensward), // The Speaker (Upper Thaliak River) - Stonefly Nymph > Hedgemole Cricket
        new(17586, 131, 400, 0f, 24f, new uint[] { 6 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12711 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Thousand Fin (Weston Waters) - Brute Leech
        new(17587, 134, 400, 0f, 24f, new uint[] { 6 }, new uint[] { 1 }, Array.Empty<(uint, int)>(), 3.5f, new uint[] { 12712 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Bloodchaser (Tharl Oom Khash) - Giant Crane Fly
        new(17588, 124, 398, 10f, 15f, new uint[] { 1, 2 }, Array.Empty<uint>(), new (uint, int)[] { (12800, 3), (12754, 5) }, 3.5f, new uint[] { 28634 }, new uint[] { 12754 }, Expansion: BigFishExpansion.Heavensward), // Problematicus (Halo) - Metal Spinner > Granite Crab
        new(17589, 146, 402, 0f, 24f, new uint[] { 9 }, Array.Empty<uint>(), new (uint, int)[] { (13727, 3) }, 3.5f, new uint[] { 30136 }, new uint[] { 12776 }, Expansion: BigFishExpansion.Heavensward), // Opabinia (The Flagship) - Signature Skyball > Platinum Fish
        new(17590, 127, 399, 1f, 4f, new uint[] { 1 }, Array.Empty<uint>(), new (uint, int)[] { (12757, 6) }, 3.5f, new uint[] { 12705 }, new uint[] { 12757 }, Expansion: BigFishExpansion.Heavensward), // Armor Fish (Upper Thaliak River) - Purse Web Spider > Hedgemole Cricket
        new(17591, 139, 401, 5f, 7f, new uint[] { 1 }, Array.Empty<uint>(), new (uint, int)[] { (12810, 3), (12753, 3) }, 3.5f, new uint[] { 12712 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Heavensward), // Sea Butterfly (Mok Oogl Island) - Giant Crane Fly
        new(17592, 112, 397, 0f, 3f, new uint[] { 16 }, Array.Empty<uint>(), new (uint, int)[] { (12715, 5) }, 3.5f, new uint[] { 12705 }, new uint[] { 12715 }, Expansion: BigFishExpansion.Heavensward), // Charibenet (Clearpool) - Purse Web Spider > Ice Faerie
        new(17593, 134, 400, 5f, 8f, new uint[] { 6 }, Array.Empty<uint>(), new (uint, int)[] { (12805, 5) }, 3.5f, new uint[] { 12712 }, new uint[] { 12805 }, Expansion: BigFishExpansion.Heavensward), // Raimdellopterus (Tharl Oom Khash) - Giant Crane Fly > Rudderfish
    };

    public static readonly BigFish[] Stormblood =
    {
        new(20143, 156, 137, 0f, 24f, new uint[] { 7, 8 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4f, new uint[] { 2585 }, new uint[] { 4869, 4904 }, Expansion: BigFishExpansion.Stormblood), // Little Perykos (North Isle of Endless Summer) - Lugworm > Merlthor Goby > Wahoo
        new(23057, 182, 635, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20615 }, new uint[] { 20056 }, Expansion: BigFishExpansion.Stormblood), // Hookstealer (Upper Mirage Creek) - Midge Larva > Gyr Abanian Trout
        new(23058, 186, 612, 0f, 24f, new uint[] { 9 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Sapphire Fan (Dimwold) - Stonefly Larva
        new(23059, 187, 612, 12f, 16f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // The Archbishop (The Comet's Tail) - Suspending Minnow
        new(23060, 190, 620, 0f, 24f, new uint[] { 11 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Bondsplitter (Grymm & Enid) - Suspending Minnow
        new(23061, 191, 620, 8f, 12f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20615 }, new uint[] { 20056 }, Expansion: BigFishExpansion.Stormblood), // The Undecided (The Slow Wash) - Midge Larva > Gyr Abanian Trout
        new(23062, 196, 621, 0f, 24f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20616 }, new uint[] { 20025 }, Expansion: BigFishExpansion.Stormblood), // Diamond-eye (Loch Seld) - Silkworm > Rock Saltfish
        new(23063, 157, 628, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20617 }, new uint[] { 20112 }, Expansion: BigFishExpansion.Stormblood), // Rising Dragon (Kugane Piers) - Live Shrimp > Ruby Shrimp
        new(23064, 197, 641, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20676 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // The Gambler (Shirogane) - Blue Bobbit
        new(23065, 161, 613, 16f, 20f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20676 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // The Winter Queen (Shoal Rock) - Blue Bobbit
        new(23066, 164, 613, 0f, 24f, new uint[] { 9 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20617 }, new uint[] { 20112 }, Expansion: BigFishExpansion.Stormblood), // Rakshasa (The Isle of Zekki) - Live Shrimp > Ruby Shrimp
        new(23067, 170, 614, 12f, 14f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Bokuden (Doma Castle) - Stonefly Larva
        new(23068, 174, 614, 0f, 24f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Hagoromo Koi (Plum Spring) - Stonefly Larva
        new(23069, 179, 622, 20f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // The Word of God (Tao Khaal) - Stonefly Larva
        new(23070, 180, 622, 0f, 24f, new uint[] { 5 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.3f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Yat Khan (Lower Yat Khaal) - Stonefly Larva
        new(24205, 183, 635, 0f, 24f, new uint[] { 9 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20615 }, new uint[] { 20056 }, Expansion: BigFishExpansion.Stormblood), // Watcher Catfish (Rhalgr's Reach) - Midge Larva > Gyr Abanian Trout
        new(24206, 184, 635, 8f, 12f, new uint[] { 3, 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20613 }, new uint[] { 20064 }, Expansion: BigFishExpansion.Stormblood), // Bloodtail Zombie (The Outer Fist) - Salmon Roe > Balloon Frog
        new(24207, 185, 612, 16f, 20f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Hardhead Trout (Timmon Beck) - Stonefly Larva
        new(24208, 188, 612, 0f, 24f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Downstream Loach (The Velodyna River) - Stonefly Larva
        new(24209, 189, 612, 20f, 24f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Corpse Chub (Mirage Creek) - Suspending Minnow
        new(24210, 192, 620, 0f, 24f, new uint[] { 2 }, new uint[] { 4 }, Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20613 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // The Last Tear (Heather Falls) - Salmon Roe
        new(24211, 194, 620, 16f, 20f, new uint[] { 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Hemon (The Bull's Bath) - Suspending Minnow
        new(24212, 193, 620, 0f, 24f, new uint[] { 1 }, new uint[] { 3, 5, 4, 11 }, Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Moksha (The Ephor) - Suspending Minnow
        new(24213, 198, 641, 4f, 6f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20614 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Princess Killifish (The Silver Canal) - Nightcrawler
        new(24214, 158, 613, 0f, 8f, new uint[] { 3 }, new uint[] { 9 }, Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20676 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Ku'er (The Ruby Price) - Blue Bobbit
        new(24215, 162, 613, 0f, 24f, new uint[] { 5 }, new uint[] { 2, 1 }, Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20617 }, new uint[] { 20112 }, Expansion: BigFishExpansion.Stormblood), // Argonautica (Onokoro) - Live Shrimp > Ruby Shrimp
        new(24216, 173, 614, 0f, 24f, new uint[] { 2, 1 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Hagoromo Bijin (The One River (West)) - Stonefly Larva
        new(24217, 178, 622, 8f, 16f, new uint[] { 3 }, new uint[] { 7, 6 }, Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20614 }, new uint[] { 20127 }, Expansion: BigFishExpansion.Stormblood), // Duskfish (Azim Khaat) - Nightcrawler > Zagas Khaal
        new(24218, 177, 622, 4f, 8f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.4f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Blade Skipper (Upper Yat Khaal) - Suspending Minnow
        new(24881, 195, 620, 0f, 24f, new uint[] { 2 }, new uint[] { 1 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Lily of the Veil (The Arms of Meed) - Suspending Minnow
        new(24882, 159, 613, 20f, 24f, new uint[] { 9 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20617 }, new uint[] { 20112 }, Expansion: BigFishExpansion.Stormblood), // The Vegetarian (Hells' Lid) - Live Shrimp > Ruby Shrimp
        new(24883, 160, 613, 10f, 18f, new uint[] { 2 }, new uint[] { 9 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20676 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Seven Stars (The Isle of Bekko) - Blue Bobbit
        new(24884, 163, 613, 16f, 24f, new uint[] { 9 }, new uint[] { 2, 1 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20617 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Pinhead (Isari) - Live Shrimp
        new(24885, 165, 614, 0f, 24f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20614 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Pomegranate Trout (The Heron's Nest) - Nightcrawler
        new(24886, 166, 614, 0f, 24f, new uint[] { 1 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Glarramundi (The Heron's Way) - Suspending Minnow
        new(24887, 167, 614, 20f, 24f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Hermit's End (Namai) - Stonefly Larva
        new(24888, 171, 614, 16f, 24f, new uint[] { 8 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Suiten Ippeki (Mercantile Docks) - Stonefly Larva
        new(24889, 172, 614, 0f, 8f, new uint[] { 2 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Axelrod (The One River (East)) - Stonefly Larva
        new(24890, 169, 614, 12f, 16f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // The Unraveled Bow (Prism Canyon) - Suspending Minnow
        new(24891, 181, 622, 4f, 8f, new uint[] { 2, 1 }, new uint[] { 7 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Nhaama's Treasure (Dotharl Khaa) - Suspending Minnow
        new(24892, 175, 622, 8f, 12f, new uint[] { 1 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20615 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Garden Skipper (Nem Khaal) - Midge Larva
        new(24893, 176, 622, 0f, 8f, new uint[] { 4, 3, 5 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20614 }, new uint[] { 20127 }, Expansion: BigFishExpansion.Stormblood), // Banderole (Hak Khaal) - Nightcrawler > Zagas Khaal
        new(24990, 185, 612, 16f, 20f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20675 }, new uint[] { 24207 }, Expansion: BigFishExpansion.Stormblood), // Xenacanthus (Timmon Beck) - Stonefly Larva > Hardhead Trout
        new(24991, 190, 620, 0f, 24f, new uint[] { 11 }, Array.Empty<uint>(), new (uint, int)[] { (23060, 2) }, 4.5f, new uint[] { 20619 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Drepanaspis (Grymm & Enid) - Suspending Minnow
        new(24992, 196, 621, 16f, 18f, Array.Empty<uint>(), Array.Empty<uint>(), new (uint, int)[] { (20040, 2) }, 4.5f, new uint[] { 20616 }, new uint[] { 20025 }, Expansion: BigFishExpansion.Stormblood), // Stethacanthus (Loch Seld) - Silkworm > Rock Saltfish
        new(24993, 158, 613, 4f, 8f, new uint[] { 3 }, new uint[] { 9 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20676 }, new uint[] { 24214 }, Expansion: BigFishExpansion.Stormblood), // The Ruby Dragon (The Ruby Price) - Blue Bobbit > Ku'er
        new(24994, 168, 614, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), new (uint, int)[] { (24203, 3), (23056, 3), (24204, 5) }, 4.5f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // Warden of the Seven Hues (Prism Lake) - Stonefly Larva
        new(24995, 181, 622, 5.5f, 6.5f, new uint[] { 1 }, new uint[] { 7 }, Array.Empty<(uint, int)>(), 4.5f, new uint[] { 20675 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Stormblood), // The Unconditional (Dotharl Khaa) - Stonefly Larva
    };

    public static readonly BigFish[] Shadowbringers =
    {
        new(28065, 201, 819, 18f, 22f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.1f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Loose Pendant (Crystarium Personal Suites) - Baitbugs
        new(28066, 214, 820, 12f, 20f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.1f, new uint[] { 27590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Winged Dame (The Derelicts) - Squid Strip
        new(28067, 204, 813, 0f, 24f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.1f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // The Unforgiven (The Source) - Baitbugs
        new(28068, 210, 814, 0f, 24f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.1f, new uint[] { 27585 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Bronze Sole (Sharptongue Drip) - Marble Nymph
        new(28069, 215, 815, 0f, 6f, new uint[] { 11 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.1f, new uint[] { 27586 }, new uint[] { 27460 }, Expansion: BigFishExpansion.Shadowbringers), // The Horned King (The River of Sand) - Jerked Ovim > Hornhelm
        new(28070, 219, 816, 20f, 24f, new uint[] { 2, 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.1f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // The Sound of Fury (Longmirror Lake) - Baitbugs
        new(28071, 225, 817, 10f, 12f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.1f, new uint[] { 27587 }, new uint[] { 27490, 27491 }, Expansion: BigFishExpansion.Shadowbringers), // Priest of Yx'Lokwa (Lake Tusi Mek'ta) - Robber Ball > Clown Tetra > Eryops
        new(28072, 235, 818, 6f, 10f, new uint[] { 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.1f, new uint[] { 27590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Starchaser (Purpure) - Squid Strip
        new(28925, 206, 813, 16f, 24f, new uint[] { 3, 4 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 5.2f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // The Jaws of Undeath (The Isle of Ken) - Baitbugs
        new(28926, 209, 814, 0f, 2f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.2f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // White Ronso (Lower Watts River) - Baitbugs
        new(28927, 216, 815, 12f, 16f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.2f, new uint[] { 27584 }, new uint[] { 27461 }, Expansion: BigFishExpansion.Shadowbringers), // Ambling Caltrop (The Hills of Amber) - Desert Dessert Frog > Web-footed Sand Gecko
        new(28928, 221, 816, 0f, 24f, new uint[] { 4 }, new uint[] { 2, 1 }, Array.Empty<(uint, int)>(), 5.2f, new uint[] { 27585 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Fae Rainbow (The Jealous One) - Marble Nymph
        new(28929, 227, 817, 2f, 12f, new uint[] { 1, 2 }, new uint[] { 3, 4 }, Array.Empty<(uint, int)>(), 5.2f, new uint[] { 27587 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Black Jet (The Lozatl) - Robber Ball
        new(28930, 230, 818, 12f, 14f, new uint[] { 2, 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.2f, new uint[] { 27590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Ondo Sigh (The Flounders' Floor) - Squid Strip
        new(30432, 200, 819, 22.5f, 23.5f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.3f, new uint[] { 27582 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // The Sinsteeped (The Quadrivium) - Fruit Worm
        new(30433, 202, 813, 0f, 24f, new uint[] { 1, 2 }, new uint[] { 4 }, Array.Empty<(uint, int)>(), 5.3f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Sweetheart (The Rift of Sighs) - Baitbugs
        new(30434, 207, 814, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.3f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Giant Taimen (Upper Watts River) - Baitbugs
        new(30435, 218, 816, 6f, 8f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.3f, new uint[] { 27585 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Leannisg (Handmirror Lake) - Marble Nymph
        new(30436, 224, 816, 0f, 24f, new uint[] { 1 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 5.3f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Gold Hammer (Saint Fathric's Temple) - Baitbugs
        new(30437, 228, 817, 18f, 24f, new uint[] { 4 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 5.3f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Recordkiller (South Mjrl's Regret) - Baitbugs
        new(30438, 234, 818, 0f, 3f, new uint[] { 1 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 5.3f, new uint[] { 27590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // The Mother of All Pancakes (East Caliban Gap) - Squid Strip
        new(30439, 236, 818, 18f, 20f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.3f, new uint[] { 27590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Opal Shrimp (The Norvrandt Slope) - Squid Strip
        new(32049, 203, 813, 6f, 8f, new uint[] { 2 }, new uint[] { 1 }, Array.Empty<(uint, int)>(), 5.4f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Moonlight Guppy (The Rusted Reservoir) - Baitbugs
        new(32050, 208, 814, 0f, 24f, new uint[] { 4 }, new uint[] { 3, 4 }, Array.Empty<(uint, int)>(), 5.4f, new uint[] { 27585 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Steel Fan (White Oil Falls) - Marble Nymph
        new(32051, 213, 814, 22f, 24f, new uint[] { 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.4f, new uint[] { 27588 }, new uint[] { 27457 }, Expansion: BigFishExpansion.Shadowbringers), // Henodus Grandis (The Eastern Kholusian Coast) - Short Bill Minnow > Spearhead Squid
        new(32052, 220, 816, 12f, 16f, new uint[] { 10 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 5.4f, new uint[] { 27585 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Sunken Tome (The Haughty One) - Marble Nymph
        new(32053, 226, 817, 17f, 20f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.4f, new uint[] { 27587 }, new uint[] { 27492 }, Expansion: BigFishExpansion.Shadowbringers), // Pearl Pipira (The Red Chalice) - Robber Ball > Diamond Pipira
        new(32054, 231, 818, 8f, 10f, new uint[] { 3 }, new uint[] { 1 }, Array.Empty<(uint, int)>(), 5.4f, new uint[] { 27590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // The Ondotaker (Where the Dry Return) - Squid Strip
        new(33316, 199, 819, 22f, 24f, new uint[] { 1 }, new uint[] { 1 }, Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27585 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Aster Trivi (The Trivium) - Marble Nymph
        new(33317, 205, 813, 0f, 24f, new uint[] { 10 }, new uint[] { 7 }, Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27582 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Python Discus (Sullen) - Fruit Worm
        new(33318, 211, 814, 6f, 8f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27583 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Steel Razor (The Western Kholusian Coast) - Moyebi Shrimp
        new(33319, 212, 814, 10f, 14f, new uint[] { 6 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Shadeshifter (Seagazer Shoals) - Squid Strip
        new(33320, 217, 815, 6f, 10f, new uint[] { 14 }, new uint[] { 1, 2, 14 }, Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27586 }, new uint[] { 27464 }, Expansion: BigFishExpansion.Shadowbringers), // Nabaath Saw (The Nabaath Severance) - Jerked Ovim > Desert Saw
        new(33321, 223, 816, 0f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Dammroen Herring (The Spoiled One) - Baitbugs
        new(33322, 222, 816, 7f, 17f, new uint[] { 1 }, new uint[] { 10 }, Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Celestial (Father Collard's Failings) - Baitbugs
        new(33323, 229, 817, 2f, 6f, new uint[] { 4 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Deephaunt (Woven Oath) - Baitbugs
        new(33324, 245, 817, 6f, 7f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27587 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Golden Pipira (Mjrl's Tears) - Robber Ball
        new(33325, 232, 818, 22f, 24f, new uint[] { 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27588 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Mora Tecta (Northwest Caliban Gorge) - Short Bill Minnow
        new(33326, 233, 818, 16f, 20f, new uint[] { 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.5f, new uint[] { 27588 }, new uint[] { 27506 }, Expansion: BigFishExpansion.Shadowbringers), // Maru Crab (West Caliban Gap) - Short Bill Minnow > Ancient Shrimp
        new(33239, 206, 813, 16f, 24f, new uint[] { 4 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 5.55f, new uint[] { 27589 }, new uint[] { 28925 }, Expansion: BigFishExpansion.Shadowbringers), // Listracanthus (The Isle of Ken) - Baitbugs > The Jaws of Undeath
        new(33240, 212, 814, 10f, 16f, Array.Empty<uint>(), Array.Empty<uint>(), new (uint, int)[] { (33319, 1), (27452, 5) }, 5.55f, new uint[] { 27588 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Aquamaton (Seagazer Shoals) - Short Bill Minnow
        new(33241, 215, 815, 0f, 2f, new uint[] { 14 }, new uint[] { 11 }, new (uint, int)[] { (27462, 10) }, 5.55f, new uint[] { 27584 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Cinder Surprise (The River of Sand) - Desert Dessert Frog
        new(33242, 219, 816, 23.5f, 24f, new uint[] { 1 }, new uint[] { 10 }, Array.Empty<(uint, int)>(), 5.55f, new uint[] { 27589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Ealad Skaan (Longmirror Lake) - Baitbugs
        new(33243, 225, 817, 10f, 12f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 5.55f, new uint[] { 27587 }, new uint[] { 27490, 27491, 28071 }, Expansion: BigFishExpansion.Shadowbringers), // Greater Serpent of Ronka (Lake Tusi Mek'ta) - Robber Ball > Clown Tetra > Eryops > Priest of Yx'Lokwa
        new(33244, 232, 818, 0f, 2f, new uint[] { 3 }, new uint[] { 2 }, new (uint, int)[] { (33325, 2) }, 5.55f, new uint[] { 27590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Shadowbringers), // Lancetfish (Northwest Caliban Gorge) - Squid Strip
    };

    public static readonly BigFish[] Endwalker =
    {
        new(36679, 252, 962, 20f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.1f, new uint[] { 36593 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Aetherolectric Guitarfish (Scholar's Harbor) - Mackerel Strip
        new(36680, 255, 956, 18f, 22f, new uint[] { 3 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.1f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Jumbo Snook (Unmoved Source Alpha) - Mayfly
        new(36681, 260, 963, 4f, 8f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.1f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Earful (Meghaduta) - Mayfly
        new(36682, 264, 957, 0f, 24f, new uint[] { 8 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.1f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Hippo Frog (Giantsgall Grounds) - Mayfly
        new(36683, 270, 958, 0f, 24f, new uint[] { 15 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.1f, new uint[] { 36591 }, new uint[] { 36458 }, Expansion: BigFishExpansion.Endwalker), // Rimepike (The Eblan Thaw) - Mayfly > Cerule Core
        new(36684, 279, 960, 10f, 14f, new uint[] { 49 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.1f, new uint[] { 36595 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Foun Ahlm (Apohelos 18-β) - Chimera Worm
        new(36685, 283, 960, 8f, 12f, new uint[] { 149 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.1f, new uint[] { 36597 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Forbiddingway (Limne 18) - Stardust
        new(37845, 253, 962, 16f, 20f, new uint[] { 15 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.2f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Greatsword Snook (Oinops) - Mayfly
        new(37846, 257, 956, 8f, 16f, new uint[] { 3 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 6.2f, new uint[] { 36590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Swampsucker Bowfin (Unmoved Source Beta) - Sky Spoon Lure
        new(37847, 261, 957, 0f, 24f, new uint[] { 4 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 6.2f, new uint[] { 36592 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Lale Crab (Yedlihmad) - Shrimp Ball
        new(37848, 266, 957, 8f, 16f, new uint[] { 7, 8 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 6.2f, new uint[] { 36590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Bigcuda (Ksiroda) - Sky Spoon Lure
        new(37849, 271, 958, 2f, 8f, new uint[] { 15 }, new uint[] { 3, 4 }, Array.Empty<(uint, int)>(), 6.2f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Sovereign Shadow (The Stainless Course) - Mayfly
        new(37850, 272, 959, 0f, 2f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.2f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Disappirarucu (Greatest Endsvale) - Mayfly
        new(37851, 281, 960, 2f, 4f, new uint[] { 149 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.2f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Starscryer (The Wellspring of Regret) - Mayfly
        new(37852, 284, 960, 2f, 4f, new uint[] { 49 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.2f, new uint[] { 36597 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Argonauta argo (Limne 3-α) - Stardust
        new(37853, 275, 961, 0f, 24f, new uint[] { 49 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.2f, new uint[] { 36591 }, new uint[] { 36478 }, Expansion: BigFishExpansion.Endwalker), // Planetes (Rumination's Ramble) - Mayfly > Albino Loach
        new(38830, 254, 962, 8f, 14f, new uint[] { 1 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 6.3f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Catastrophizer (Reflecting Pool) - Mayfly
        new(38831, 256, 956, 0f, 24f, new uint[] { 7 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 6.3f, new uint[] { 36590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Mossgill Salmon (The Mover Alpha) - Sky Spoon Lure
        new(38832, 263, 957, 20f, 24f, new uint[] { 1 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 6.3f, new uint[] { 36592 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Vidyutvat Wrasse (The Great Runoff) - Shrimp Ball
        new(38833, 267, 957, 22f, 2f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.3f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Browned Banana Eel (Pavana's Remorse) - Mayfly
        new(38834, 274, 959, 10f, 13f, new uint[] { 49 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.3f, new uint[] { 36595 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Frozen Regotoise (The Frozen Fissure) - Chimera Worm
        new(38835, 278, 960, 20f, 4f, new uint[] { 149 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.3f, new uint[] { 36595 }, new uint[] { 36489 }, Expansion: BigFishExpansion.Endwalker), // Cosmic Haze (Apohelos 18-γ) - Chimera Worm > Vacuum Shrimp
        new(38836, 277, 961, 4f, 10f, new uint[] { 1 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 6.3f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Antheian Dahlia (Lethe) - Mayfly
        new(39879, 258, 956, 22f, 2f, new uint[] { 2 }, new uint[] { 7 }, Array.Empty<(uint, int)>(), 6.4f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Onyx Knifefish (The Mover Beta) - Mayfly
        new(39880, 265, 957, 0f, 24f, new uint[] { 3 }, new uint[] { 4 }, Array.Empty<(uint, int)>(), 6.4f, new uint[] { 36589 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Wakeful Warden (The Wakeful Torana) - Leech
        new(39881, 269, 957, 0f, 24f, new uint[] { 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 6.4f, new uint[] { 36593 }, new uint[] { 36451, 36454 }, Expansion: BigFishExpansion.Endwalker), // Basilosaurus Rex (The Perfumed Tides) - Mackerel Strip > Puff-paya > Basilosaurus
        new(39882, 280, 960, 12f, 20f, new uint[] { 49 }, new uint[] { 149 }, Array.Empty<(uint, int)>(), 6.4f, new uint[] { 36595 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Eehs Fan (Apohelos 18-α) - Chimera Worm
        new(39883, 276, 961, 20f, 22f, new uint[] { 1, 2 }, new uint[] { 49 }, Array.Empty<(uint, int)>(), 6.4f, new uint[] { 36590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Gilt Dermogenys (The Lower Hungering Gardens) - Sky Spoon Lure
        new(41401, 259, 956, 8f, 12f, new uint[] { 2 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 6.5f, new uint[] { 36591 }, new uint[] { 36412 }, Expansion: BigFishExpansion.Endwalker), // Circuit Tilapia (Deepmoat) - Mayfly > Astacus Aetherius
        new(41402, 262, 957, 0f, 4f, new uint[] { 1 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 6.5f, new uint[] { 36592 }, new uint[] { 36426 }, Expansion: BigFishExpansion.Endwalker), // Durdina Fish (The Thavnairian Coast) - Shrimp Ball > Shadowdart Sardine
        new(41403, 268, 957, 4f, 8f, new uint[] { 2 }, new uint[] { 3 }, new (uint, int)[] { (36449, 5) }, 6.5f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Mayaman (The Font of Maya) - Mayfly
        new(41404, 273, 959, 2f, 8f, new uint[] { 148 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 6.5f, new uint[] { 36595 }, new uint[] { 36470 }, Expansion: BigFishExpansion.Endwalker), // Chlorophos Deathworm (The Chlorophospond) - Chimera Worm > Calicia
        new(41405, 282, 960, 18f, 22f, new uint[] { 2 }, new uint[] { 149 }, Array.Empty<(uint, int)>(), 6.5f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Starscale Ephemeris (Abode of the Ea) - Mayfly
        new(41406, 285, 960, 12f, 16f, new uint[] { 49 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 6.5f, new uint[] { 36597 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // E.B.E.-852738 (Limne 3-β) - Stardust
        new(41407, 259, 956, 9f, 12f, new uint[] { 2 }, new uint[] { 1 }, new (uint, int)[] { (36412, 3) }, 6.55f, new uint[] { 36591 }, new uint[] { 36412 }, Expansion: BigFishExpansion.Endwalker), // Hyphalosaurus (Deepmoat) - Mayfly > Astacus Aetherius
        new(41408, 269, 957, 14f, 16f, new uint[] { 2 }, new uint[] { 8 }, new (uint, int)[] { (36454, 12) }, 6.55f, new uint[] { 36593 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Gharlichthys (The Perfumed Tides) - Mackerel Strip
        new(41409, 270, 958, 16f, 24f, new uint[] { 15 }, new uint[] { 2 }, new (uint, int)[] { (36458, 3) }, 6.55f, new uint[] { 36591 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Snowy Parexus (The Eblan Thaw) - Mayfly
        new(41410, 277, 961, 15.5f, 16.5f, new uint[] { 49 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 6.55f, new uint[] { 36590 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Furcacauda (Lethe) - Sky Spoon Lure
        new(41411, 273, 959, 8f, 10f, new uint[] { 2 }, new uint[] { 148 }, Array.Empty<(uint, int)>(), 6.55f, new uint[] { 36595 }, Array.Empty<uint>(), Expansion: BigFishExpansion.Endwalker), // Lopoceras Elegans (The Chlorophospond) - Chimera Worm
        new(41412, 285, 960, 0f, 8f, new uint[] { 149 }, new uint[] { 49 }, new (uint, int)[] { (36521, 1), (36520, 2), (36519, 3) }, 6.55f, new uint[] { 36597, 36596 }, new uint[] { 36518 }, Expansion: BigFishExpansion.Endwalker), // Sidereal Whale (Limne 3-β) - Stardust/Panic Jig > Horizon Event
    };

    public static readonly BigFish[] Dawntrail =
    {
        new(44339, 294, 1185, 0f, 24f, new uint[] { 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.1f, new uint[] { 43858 }, Array.Empty<uint>()), // Icuvlo's Barter (Downripple) - Red Maggots
        new(44340, 297, 1187, 12f, 14f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.1f, new uint[] { 43854 }, Array.Empty<uint>()), // Moongripper (Sunken Stars) - White Worm
        new(44341, 301, 1188, 16f, 20f, new uint[] { 3, 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.1f, new uint[] { 43858 }, Array.Empty<uint>()), // Cazuela Crab (Waters Hanu) - Red Maggots
        new(44342, 318, 1189, 20f, 24f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.1f, new uint[] { 43850, 43859 }, new uint[] { 43746, 43747 }), // Stardust Sleeper (Xty'iinbek Tsoly) - Crimson Lugworm/Ghost Nipper > Sharknose Goby > Yak T'el Crab
        new(44343, 308, 1189, 0f, 24f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.1f, new uint[] { 43858 }, Array.Empty<uint>()), // Ilyon Asoh Cichlid (Xd'aa Talat Tsoly) - Red Maggots
        new(44344, 327, 1186, 0f, 4f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.1f, new uint[] { 43858 }, Array.Empty<uint>()), // Pixel Loach (Residential Sector) - Red Maggots
        new(44345, 319, 1190, 4f, 8f, new uint[] { 1, 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.1f, new uint[] { 43858 }, Array.Empty<uint>()), // Hwittayoanaan Cichlid (Niikwerepi) - Red Maggots
        new(44346, 324, 1191, 9f, 11f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.1f, new uint[] { 43858 }, Array.Empty<uint>()), // Thunderswift Trout (The Driftdowns) - Red Maggots
        new(47988, 295, 1185, 5f, 7f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.2f, new uint[] { 43859 }, Array.Empty<uint>()), // Cabinkeep Permit (The For'ard Cabins) - Ghost Nipper
        new(47989, 300, 1188, 12f, 14f, new uint[] { 1 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.2f, new uint[] { 43852, 43849 }, new uint[] { 43691 }), // Muttering Matamata (Bopo'uihih) - Honeybee/Golden Stonefly Nymph > Poison Dyefrog
        new(47990, 302, 1188, 0f, 4f, new uint[] { 3 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 7.2f, new uint[] { 43858 }, Array.Empty<uint>()), // Riverlong Candiru (Miyakabek'zu) - Red Maggots
        new(47991, 309, 1189, 10f, 12f, Array.Empty<uint>(), Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.2f, new uint[] { 43858 }, Array.Empty<uint>()), // Deep Canopy (Iq Br'aax Reservoir) - Red Maggots
        new(47992, 310, 1189, 0f, 24f, new uint[] { 3, 4 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.2f, new uint[] { 43858 }, Array.Empty<uint>()), // Awaksbane Apoda (Yak Awak Tsoly) - Red Maggots
        new(47993, 320, 1190, 20f, 24f, new uint[] { 11 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 7.2f, new uint[] { 43855 }, new uint[] { 43751 }), // Ttokatoa (Lake Toari) - Popper Lure > Niikwerepi Trout
        new(47994, 325, 1191, 0f, 24f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.2f, new uint[] { 43858 }, Array.Empty<uint>()), // Thunderous Flounder (Crackling Canyons) - Red Maggots
        new(47995, 328, 1192, 16f, 18f, new uint[] { 2 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.2f, new uint[] { 43858 }, Array.Empty<uint>()), // Harlequin Queen (The Knowable) - Red Maggots
        new(46189, 299, 1187, 12f, 16f, new uint[] { 4 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 7.3f, new uint[] { 43858 }, Array.Empty<uint>()), // Prime Adjudicator (Karvarhur the First) - Red Maggots
        new(46190, 303, 1188, 6f, 8f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.3f, new uint[] { 43858 }, Array.Empty<uint>()), // Crenicichla Miyaka (The Dewspun Bank) - Red Maggots
        new(46191, 311, 1189, 16f, 18f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.3f, new uint[] { 43858 }, Array.Empty<uint>()), // Iron Shadowtongue (Iq Rrax Tsoly) - Red Maggots
        new(46192, 312, 1189, 0f, 4f, new uint[] { 3 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 7.3f, new uint[] { 43849, 43852 }, new uint[] { 43728 }), // Lotl-in-waiting (Xobr'it Tsoly) - Golden Stonefly Nymph/Honeybee > Cloud-eye Carp
        new(46193, 322, 1190, 18f, 24f, new uint[] { 6 }, new uint[] { 1, 2 }, Array.Empty<(uint, int)>(), 7.3f, new uint[] { 43857 }, Array.Empty<uint>()), // Azure Diver (Eastbound Zorgor) - Dragonfly
        new(46194, 323, 1191, 20f, 24f, new uint[] { 10 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.3f, new uint[] { 43858 }, Array.Empty<uint>()), // Sprouting Perch (Outskirts Shallows) - Red Maggots
        new(46195, 329, 1192, 4f, 6f, new uint[] { 7 }, Array.Empty<uint>(), new (uint, int)[] { (43781, 3) }, 7.3f, new uint[] { 43858 }, Array.Empty<uint>()), // Gigagiant Snakehead (Mu Springs Eternal) - Red Maggots
        new(46196, 331, 1192, 8f, 12f, new uint[] { 2 }, new uint[] { 7 }, Array.Empty<(uint, int)>(), 7.3f, new uint[] { 43859 }, Array.Empty<uint>()), // Gondola Louvar (Canal Town South) - Ghost Nipper
        new(49794, 296, 1185, 16f, 18f, new uint[] { 7 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 7.4f, new uint[] { 43859 }, Array.Empty<uint>()), // Purse of Riches (High Tide Harbor) - Ghost Nipper
        new(49795, 304, 1188, 8f, 12f, new uint[] { 7 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 7.4f, new uint[] { 43849, 43852 }, new uint[] { 43701 }), // Punutiy Pain (Peaks Poga) - Golden Stonefly Nymph/Honeybee > Hunu Peacock Bass
        new(49796, 305, 1188, 4f, 6f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.4f, new uint[] { 43858 }, Array.Empty<uint>()), // Shuckfin Dace (Ku'uxage) - Red Maggots
        new(49797, 313, 1189, 0f, 2f, new uint[] { 4 }, Array.Empty<uint>(), new (uint, int)[] { (43735, 3) }, 7.4f, new uint[] { 43858 }, Array.Empty<uint>()), // Shin Snuffler (Ankledeep) - Red Maggots
        new(49798, 314, 1189, 20f, 22f, new uint[] { 7 }, Array.Empty<uint>(), Array.Empty<(uint, int)>(), 7.4f, new uint[] { 43852 }, new uint[] { 43736 }), // Moxutural Greatgar (Cenote Moxutural) - Honeybee > Checkered Cichlid
        new(49799, 326, 1191, 12f, 16f, new uint[] { 2 }, new uint[] { 4 }, Array.Empty<(uint, int)>(), 7.4f, new uint[] { 43855 }, Array.Empty<uint>()), // Heirloom Goldgrouper (Alexandrian Ruins) - Popper Lure
        new(49800, 330, 1192, 2f, 4f, new uint[] { 7 }, new uint[] { 4 }, Array.Empty<(uint, int)>(), 7.4f, new uint[] { 43858 }, Array.Empty<uint>()), // Datnioides Aeroplanos (Leynode Aero) - Red Maggots
        new(49801, 333, 1192, 22f, 24f, new uint[] { 3 }, new uint[] { 7 }, new (uint, int)[] { (43796, 3), (43798, 3) }, 7.4f, new uint[] { 43858 }, Array.Empty<uint>()), // Esperance Carp (Proto Alexandria) - Red Maggots
        new(51999, 298, 1187, 0f, 2f, new uint[] { 15 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 7.5f, new uint[] { 43854 }, Array.Empty<uint>()), // Ole Ole Ole (Chirwagur Lake) - White Worm
        new(52000, 306, 1188, 13f, 15f, new uint[] { 4 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 7.5f, new uint[] { 43849 }, new uint[] { 43709 }), // Iron Oxydoras (Miyakabek'zoma) - Golden Stonefly Nymph > Dumplingfish
        new(52001, 307, 1188, 4f, 6f, new uint[] { 3 }, new uint[] { 7 }, Array.Empty<(uint, int)>(), 7.5f, new uint[] { 43855 }, Array.Empty<uint>()), // Excavator Catfish (Marsh Ligaka) - Popper Lure
        new(52002, 315, 1189, 16f, 21f, new uint[] { 7 }, new uint[] { 1 }, Array.Empty<(uint, int)>(), 7.5f, new uint[] { 43852 }, new uint[] { 43740 }), // Moonmarking Saucer (Cenote Jayunja) - Honeybee > Flawless Saucer
        new(52003, 316, 1189, 16f, 18f, new uint[] { 4 }, new uint[] { 7 }, Array.Empty<(uint, int)>(), 7.5f, new uint[] { 43858 }, Array.Empty<uint>()), // Autarch's Supper (Sapsweet Cenote) - Red Maggots
        new(52004, 317, 1189, 16f, 18f, new uint[] { 1 }, new uint[] { 4 }, Array.Empty<(uint, int)>(), 7.5f, new uint[] { 29717 }, new uint[] { 43743 }), // Bitterbark Caiman  (Bitterbark Cenote) - Versatile Lure > Blind Brotula
        new(52005, 321, 1190, 6f, 8f, new uint[] { 3 }, new uint[] { 6 }, new (uint, int)[] { (43760, 3) }, 7.5f, new uint[] { 43857 }, Array.Empty<uint>()), // Vagrant Keeper (Westbound Zorgor) - Dragonfly
        new(52006, 332, 1192, 8f, 13f, new uint[] { 4 }, new uint[] { 3 }, Array.Empty<(uint, int)>(), 7.5f, new uint[] { 43859 }, Array.Empty<uint>()), // Shined Copper Shark (Canal Town North) - Ghost Nipper
        new(52007, 299, 1187, 15f, 16f, new uint[] { 5 }, new uint[] { 4 }, Array.Empty<(uint, int)>(), 7.55f, new uint[] { 43858 }, Array.Empty<uint>()), // Ner Lar Dor (Karvarhur the First) - Red Maggots
        new(52008, 302, 1188, 13f, 15f, new uint[] { 8 }, new uint[] { 3 }, new (uint, int)[] { (43697, 6) }, 7.55f, new uint[] { 43855 }, new uint[] { 43697 }), // Xehabopo'u (Miyakabek'zu) - Popper Lure > Driftwood Catfish
        new(52009, 315, 1189, 16f, 21f, new uint[] { 7 }, new uint[] { 1 }, new (uint, int)[] { (52002, 1), (43740, 3) }, 7.55f, new uint[] { 43858 }, new uint[] { 43740 }), // Skyfrond (Cenote Jayunja) - Red Maggots > Flawless Saucer
        new(52010, 320, 1190, 22f, 24f, new uint[] { 11 }, new uint[] { 2 }, Array.Empty<(uint, int)>(), 7.55f, new uint[] { 43855 }, new uint[] { 43751, 47993 }), // Rroneek Bichir (Lake Toari) - Popper Lure > Niikwerepi Trout > Ttokatoa
        new(52011, 332, 1192, 8f, 13f, new uint[] { 4 }, new uint[] { 3 }, new (uint, int)[] { (52006, 1), (43795, 2) }, 7.55f, new uint[] { 43859 }, Array.Empty<uint>()), // Triple Threat (Canal Town North) - Ghost Nipper
        new(52297, 326, 1191, 2f, 4f, new uint[] { 50 }, new uint[] { 10 }, new (uint, int)[] { (43775, 1) }, 7.55f, new uint[] { 43858 }, Array.Empty<uint>()), // Great Ball of Lightning (Alexandrian Ruins) - Red Maggots
    };

    /// <summary>Für die Addon-Tabs auf der Fischdaten-Seite - feste Reihenfolge (siehe BigFishExpansion).</summary>
    public static readonly IReadOnlyList<(BigFishExpansion Expansion, BigFish[] Fish)> ByExpansion = new (BigFishExpansion, BigFish[])[]
    {
        (BigFishExpansion.ARealmReborn, ARealmReborn),
        (BigFishExpansion.Heavensward, Heavensward),
        (BigFishExpansion.Stormblood, Stormblood),
        (BigFishExpansion.Shadowbringers, Shadowbringers),
        (BigFishExpansion.Endwalker, Endwalker),
        (BigFishExpansion.Dawntrail, Dawntrail),
    };

    /// <summary>Alle Big Fish über alle Addons hinweg (z.B. für Start-Seite/Statistik).</summary>
    public static readonly BigFish[] All = ByExpansion.SelectMany(e => e.Fish).ToArray();
}
